# suppress inspection "UnusedProperty" for whole file
action.Generate.Codec.text=作 Codec
action.Generate.StreamCodec.text=作 Stream Codec
action.Generate.AnvilLibCodec.text=以 AnvilLib 成 Codec
action.Generate.AnvilLibMapCodec.text=以 AnvilLib 成 Map Codec
action.Generate.AnvilLibStreamCodec.text=以 AnvilLib 成 Stream Codec
