# suppress inspection "UnusedProperty" for whole file
action.Generate.Codec.text=Generate Codec
action.Generate.StreamCodec.text=Generate Stream Codec
action.Generate.AnvilLibCodec.text=Generate AnvilLib Codec
action.Generate.AnvilLibMapCodec.text=Generate AnvilLib Map Codec
action.Generate.AnvilLibStreamCodec.text=Generate AnvilLib Stream Codec
